on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        description: 'Application Name'
        type: string
      DEV_RUNNER:
        required: false
        description: 'DEV Github Runner'
        default: 'windows-latest'
        type: string
      UAT_RUNNER:
        required: true
        description: 'UAT Github Runner'
        type: string
      PROD_RUNNER:
        required: true
        description: 'PROD Github Runner'
        type: string

jobs:

  DEV:
    runs-on: ${{ inputs.DEV_RUNNER }}
    environment: DEV

    steps:
      - name: 'DEV Deployment - ${{ runner.os }}'
        run: |
          echo "Deploying to ${{ vars.CLOUD_PLATFORM }} on $env:RUNNER_OS OS VM"

      - name: 'DEV SMOKE TEST'
        if: ${{ vars.RUN_SMOKE_TESTS }}
        run: |
          echo "Running Smoke Tests..."

  UAT:
    runs-on: ${{ inputs.UAT_RUNNER }}
    needs: DEV
    environment: UAT

    steps:
      - name: 'UAT Deployment - ${{ runner.os }}'
        run: |
          echo "Deploying to ${{ vars.CLOUD_PLATFORM }} on $RUNNER_OS OS VM"

      - name: 'UAT SMOKE TEST'
        if: ${{ inputs.RUN_SMOKE_TESTS }}
        run: |
          echo "Running Smoke Tests..."

  PROD:
    runs-on: ${{ inputs.PROD_RUNNER }}
    needs: UAT
    environment: PROD

    steps:
      - name: 'PROD Deployment - ${{ runner.os }}'
        run: |
          echo "Deploying to ${{ vars.CLOUD_PLATFORM }} on $RUNNER_OS OS VM"