name: GitHub Actions Demo - Contexts

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your First Name'
        required: true
        default: 'IBMer'
        type: string
      role:
        description: 'Choose the job role that relates to you'
        required: true
        default: 'developer'
        type: choice
        options:
          - developer
          - architect
          - devops

env:
  FIRST_VAR: 'hello'
  SECOND_VAR: 'IBM!'

jobs:
  Output-Contexts:
    runs-on: ubuntu-latest

    steps:
      - name: 'Output Github Context'
        env:
          GH_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "Github Context:"
          echo "$GH_CONTEXT"

      - name: 'Output Env Context'
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: |
          echo "Environment Variables Context:"
          echo "$ENV_CONTEXT"

      - name: 'Output Inputs Context'
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: |
          echo "Workflow Inputs Context:"
          echo "$INPUTS_CONTEXT"

  Use-Contexts:
    needs: [ Output-Contexts ]
    name: "${{ inputs.name }}'s ${{ inputs.role }} Custom Job"
    runs-on: ubuntu-latest

    steps:
      - name: '${{ env.FIRST_VAR }} ${{ env.SECOND_VAR }}'
        run: |
          echo "Hello! ${{ inputs.name }}! "

      - name: '${{ inputs.role }} Custom Step'
        run: |
          echo "Running Custom Step for Job Role: ${{ inputs.role }}"

      - name: 'Checking Previous Job Status: ${{ needs.Output-Contexts }}'
        run: |
          echo "Previous Github Action Job: ${{ needs.Output-Contexts }} has a Status of ${{ needs.Output-Contexts.result }}"
