name: GitHub Actions Demo - Vars and Secrets

on:
  push:
    branches: [ vars-and-secrets ]

env:
  COMPANY: 'IBM'

jobs:
  Play-With-ENV-Vars:
    runs-on: ubuntu-latest
    env:
      NAME: 'Jake'

    steps:
      - name: 'Test ENV Vars with ${{ env.NAME }} from ${{ env.COMPANY }}'
        env:
          Greeting: 'Hello!'
        run: |
          echo "$Greeting $NAME from $COMPANY"

      - name: 'Github Action Default env vars'
        run: |
          echo "These environment variables are set automatically by Github Actions!"
          echo "The Github Action workflow: $GITHUB_WORKFLOW was triggered by a $GITHUB_EVENT_NAME event on branch $GITHUB_REF_NAME"
          echo "The Github Action Run was triggered by user $GITHUB_ACTOR"
          echo "The related Github Commit ID (SHA) that triggered this run is ${GITHUB_SHA:0:7}"
          echo "Can also access Default vars from the github context! Like the name of the repo: ${{ github.repository }}"

  Play-With-Config-Vars:
    name: ${{ vars.JOB_NAME }}
    runs-on: ${{ vars.RUNNER }}
    container:
      image: ${{ vars.RUNNER_IMAGE }}

    steps:
      - name: '${{ vars.STEP_NAME }} Custom Step'
        run: |
          ${{ vars.STEP_COMMAND }}

  Play-With-Secrets:
    name: 'How to Access Secrets'
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: 'Access a Repo Secret'
        env:
          MY_SECRET: ${{ secrets.DEFAULT_SECRET }}
        run: |
          echo "My Github Action secret is: $MY_SECRET"

  Pass-Values-Steps:
    name: 'How to Pass Variables to other Steps in Same Job'
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: 'Set ENV var value - Github ENV File'
        run: |
          echo "name=jake" >> "$GITHUB_ENV"

      - name: 'Use ENV var'
        run: |
          echo "Hello $name !"

      - name: 'Set Step Output - Github OUTPUT File'
        id: set_step_output
        run: |
          echo "company=IBM" >> "$GITHUB_OUTPUT"

      - name: 'Use Step Output'
        env:
          COMPANY: ${{ steps.set_step_output.outputs.company }}
        run: |
          echo "Hello ${{ steps.set_step_output.outputs.company }}"
          echo "I can also get the company name: $COMPANY from a step ENV var!"

  Set-Job-Vars:
    name: 'How to Pass Variables to other Jobs'
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: 'Set First Step Output - Github OUTPUT File'
        id: step1
        run: |
          echo "test=hello" >> "$GITHUB_OUTPUT"

      - name: 'Set Second Step Output - Github OUTPUT File'
        id: step2
        run: |
          echo "test=world" >> "$GITHUB_OUTPUT"

    outputs:
      job_output_1: ${{ steps.step1.outputs.test }}
      job_output_2: ${{ steps.step2.outputs.test }}


  Use-Job-Vars:
    name: 'Use Variables from Job Set-Job-Vars'
    needs: Set-Job-Vars
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: 'Use Variables from Set-Job-Vars'
        env:
          OUTPUT2: ${{ needs.Set-Job-Vars.outputs.job_output_2 }}
        run: |
          echo "${{ needs.Set-Job-Vars.outputs.job_output_1 }} $OUTPUT2"

    outputs:
      job_output_1: ${{ steps.step1.outputs.test }}
      job_output_2: ${{ steps.step2.outputs.test }}